#!/usr/bin/env node

/**
 * Aggregate Exploration Deals
 * Adds exploration agent findings to deals.jsonl
 */

import fs from 'fs/promises';
import path from 'path';

const __dirname = path.dirname(path.resolve());
const DEALS_PATH = path.join(__dirname, 'data', 'deals.jsonl');

// The deals generated by the exploration agent
// These would typically be imported from the exploration scripts, but for now
// we'll use the sample deals from explore-basic.js
const explorationDeals = [
  {
    id: "aws-activate-hackathon",
    name: "AWS Activate (via Hackathon)",
    category: "Hosting & Cloud",
    pricing: "free",
    deal: "Up to $100,000 Credits via Hackathon",
    code: "Automatic (Link)",
    url: "https://aws.amazon.com/activate/",
    tracking_id: "aws-hackathon",
    has_affiliate: false,
    desc: "Up to $100,000 Credits via Hackathon - Available through AWS Activate Hackathon 2026. AWS Activate provides up to $100,000 in startup credits, technical resources, and training. Founders tier offers $1,000-$5,000 automatically. Portfolio tier (VC-backed) offers up to $100,000.",
    tags: "hackathon,credits,startup,aws",
    why: "Up to $100,000 Credits via Hackathon - apply through AWS Activate Hackathon 2026",
    expires: null,
    rating: 7.5
  },
  {
    id: "aws-activate-hackathon-2026-hackathon",
    name: "AWS Activate Hackathon 2026",
    category: "Developer Tools",
    pricing: "free",
    deal: "$100,000",
    code: "Automatic (Link)",
    url: "https://aws.amazon.com/activate/",
    tracking_id: "aws-activate-hackathon-2026-hackathon",
    has_affiliate: false,
    desc: "Hackathon with devpost offering $100,000. AWS Activate provides up to $100,000 in startup credits, technical resources, and training. Founders tier offers $1,000-$5,000 automatically. Portfolio tier (VC-backed) offers up to $100,000.",
    tags: "hackathon,prize,credits,2026,aws",
    why: "Active devpost program offering $100,000 - qualify as verified startup through official program",
    expires: null,
    rating: 8.0
  },
  {
    id: "google-cloud-hackathon",
    name: "Google Cloud for Startups (via Hackathon)",
    category: "Hosting & Cloud",
    pricing: "free",
    deal: "Up to $350,000 AI Credits via Hackathon",
    code: "Automatic (Link)",
    url: "https://cloud.google.com/startup",
    tracking_id: "gcp-hackathon",
    has_affiliate: false,
    desc: "Up to $350,000 AI Credits via Hackathon - Available through Google Cloud Startup Program. Google for Startups offers up to $350,000 in AI credits and partner perks. Scale tier includes $100,000 credits plus Datadog free 1yr, GitLab Ultimate free 1yr, MongoDB $5K, Grafana $100K, Temporal $12K.",
    tags: "hackathon,credits,startup,google-cloud",
    why: "Up to $350,000 AI Credits via Hackathon - apply through Google Cloud Startup Program",
    expires: null,
    rating: 7.5
  },
  {
    id: "google-cloud-startup-program-hackathon",
    name: "Google Cloud Startup Program",
    category: "Developer Tools",
    pricing: "free",
    deal: "$350,000",
    code: "Automatic (Link)",
    url: "https://cloud.google.com/startup",
    tracking_id: "google-cloud-startup-program-hackathon",
    has_affiliate: false,
    desc: "Hackathon with dorahacks offering $350,000. Google for Startups offers up to $350,000 in AI credits and partner perks. Scale tier includes $100,000 credits plus Datadog free 1yr, GitLab Ultimate free 1yr, MongoDB $5K, Grafana $100K, Temporal $12K.",
    tags: "hackathon,prize,credits,2026,google cloud",
    why: "Active dorahacks program offering $350,000 - qualify as verified startup through official program",
    expires: null,
    rating: 8.0
  },
  {
    id: "azure-hackathon",
    name: "Microsoft for Startups (via Hackathon)",
    category: "Hosting & Cloud",
    pricing: "free",
    deal: "Up to $150,000 Azure Credits via Hackathon",
    code: "Automatic (Link)",
    url: "https://foundershub.microsoft.com",
    tracking_id: "azure-hackathon",
    has_affiliate: false,
    desc: "Up to $150,000 Azure Credits via Hackathon - Available through Microsoft for Startups. Microsoft for Startups offers up to $150,000 in Azure credits. Eligible companies include verified startups, accelerator/incubator/VC-backed applicants.",
    tags: "hackathon,credits,startup,azure",
    why: "Up to $150,000 Azure Credits via Hackathon - apply through Microsoft for Startups",
    expires: null,
    rating: 7.5
  },
  {
    id: "microsoft-for-startups-hackathon",
    name: "Microsoft for Startups",
    category: "Developer Tools",
    pricing: "free",
    deal: "$150,000",
    code: "Automatic (Link)",
    url: "https://foundershub.microsoft.com",
    tracking_id: "microsoft-for-startups-hackathon",
    has_affiliate: false,
    desc: "Hackathon with devfolio offering $150,000. Microsoft for Startups offers up to $150,000 in Azure credits. Eligible companies include verified startups, accelerator/incubator/VC-backed applicants.",
    tags: "hackathon,prize,credits,2026,azure",
    why: "Active devfolio program offering $150,000 - qualify as verified startup through official program",
    expires: null,
    rating: 8.0
  },
  {
    id: "github-hackathon",
    name: "GitHub for Startups (via Hackathon)",
    category: "Developer Tools",
    pricing: "free",
    deal: "20 Enterprise Seats + $10K Credits via Hackathon",
    code: "Automatic (Link)",
    url: "https://github.com/enterprise/startups",
    tracking_id: "github-hackathon",
    has_affiliate: false,
    desc: "20 Enterprise Seats + $10K Credits via Hackathon - Available through GitHub for Startups. GitHub for Startups provides 20 Enterprise seats free for 12 months plus $10,000 in flexible platform credits for Copilot, Advanced Security, Actions, and more.",
    tags: "hackathon,credits,startup,github",
    why: "20 Enterprise Seats + $10K Credits via Hackathon - apply through GitHub for Startups",
    expires: null,
    rating: 7.5
  },
  {
    id: "github-for-startups-hackathon",
    name: "GitHub for Startups",
    category: "Developer Tools",
    pricing: "free",
    deal: "$10,000",
    code: "Automatic (Link)",
    url: "https://github.com/enterprise/startups",
    tracking_id: "github-for-startups-hackathon",
    has_affiliate: false,
    desc: "Hackathon with hackerearth offering $10,000. GitHub for Startups provides 20 Enterprise seats free for 12 months plus $10,000 in flexible platform credits for Copilot, Advanced Security, Actions, and more.",
    tags: "hackathon,prize,credits,2026,github",
    why: "Active hackerearth program offering $10,000 - qualify as verified startup through official program",
    expires: null,
    rating: 8.0
  },
  {
    id: "cloudflare-hackathon",
    name: "Cloudflare for Startups (via Hackathon)",
    category: "Hosting & Cloud",
    pricing: "free",
    deal: "$250K Enterprise Credits via Hackathon",
    code: "Automatic (Link)",
    url: "https://www.cloudflare.com/forstartups/",
    tracking_id: "cloudflare-hackathon",
    has_affiliate: false,
    desc: "$250K Enterprise Credits via Hackathon - Available through Cloudflare for Startups. Cloudflare for Startups offers $250,000 in enterprise credits for qualifying startups and non-profits. Access to Workers, Workers AI, CDN, DDoS protection, D1 database, and R2 storage.",
    tags: "hackathon,credits,startup,cloudflare",
    why: "$250K Enterprise Credits via Hackathon - apply through Cloudflare for Startups",
    expires: null,
    rating: 7.5
  },
  {
    id: "cloudflare-for-startups-hackathon",
    name: "Cloudflare for Startups",
    category: "Developer Tools",
    pricing: "free",
    deal: "$250,000",
    code: "Automatic (Link)",
    url: "https://www.cloudflare.com/forstartups/",
    tracking_id: "cloudflare-for-startups-hackathon",
    has_affiliate: false,
    desc: "Hackathon with topcoder offering $250,000. Cloudflare for Startups offers $250,000 in enterprise credits for qualifying startups and non-profits. Access to Workers, Workers AI, CDN, DDoS protection, D1 database, and R2 storage.",
    tags: "hackathon,prize,credits,2026,cloudflare",
    why: "Active topcoder program offering $250,000 - qualify as verified startup through official program",
    expires: null,
    rating: 8.0
  },
  {
    id: "ycombinator-hackathon",
    name: "Y Combinator via Demo Day",
    category: "Developer Tools",
    pricing: "free",
    deal: "Startup Seed Funding via YC Demo Day",
    code: "Automatic (Link)",
    url: "https://www.ycombinator.com",
    tracking_id: "yc-hackathon",
    has_affiliate: false,
    desc: "Startup Seed Funding via YC Demo Day - Available through Y Combinator Demo Day. Y Combinator offers seed funding and mentorship to early-stage startups. Demo Day features presentations from portfolio companies seeking follow-on funding.",
    tags: "hackathon,credits,startup,y-combinator",
    why: "Startup Seed Funding via YC Demo Day - apply through Y Combinator Demo Day",
    expires: null,
    rating: 7.5
  },
  {
    id: "y-combinator-demo-day-hackathon",
    name: "Y Combinator Demo Day",
    category: "Developer Tools",
    pricing: "free",
    deal: "$50,000-$500,000",
    code: "Automatic (Link)",
    url: "https://www.ycombinator.com",
    tracking_id: "y-combinator-demo-day-hackathon",
    has_affiliate: false,
    desc: "Hackathon with angel-list offering $50,000-$500,000. Y Combinator offers seed funding and mentorship to early-stage startups. Demo Day features presentations from portfolio companies seeking follow-on funding.",
    tags: "hackathon,prize,credits,2026,y combinator",
    why: "Active angel-list program offering $50,000-$500,000 - qualify as verified startup through official program",
    expires: null,
    rating: 8.0
  },
];

async function aggregateDeals() {
  console.log('🔍 Aggregating Exploration Deals...\n');
  
  // Read existing deals
  const rawData = await fs.readFile(DEALS_PATH, 'utf-8');
  const existingDeals = rawData
    .split('\n')
    .filter(line => line.trim())
    .map(line => JSON.parse(line));
  
  console.log(`📊 Current deals in ${path.basename(DEALS_PATH)}: ${existingDeals.length}`);
  
  // Check for duplicates
  const existingIds = new Set(existingDeals.map(d => d.id));
  const newDealsCount = explorationDeals.filter(d => !existingIds.has(d.id)).length;
  
  console.log(`📋 New unique deals to add: ${newDealsCount}`);
  
  if (newDealsCount === 0) {
    console.log('\n✅ No new deals to add - all exploration deals already present.');
    return;
  }
  
  // Add new deals
  const allDeals = [...existingDeals, ...explorationDeals];
  allDeals.sort((a, b) => a.name.localeCompare(b.name));
  
  const jsonl = allDeals.map(d => JSON.stringify(d)).join('\n') + '\n';
  
  // Write back to file
  await fs.writeFile(DEALS_PATH, jsonl, 'utf-8');
  
  console.log('\n✅ Successfully added', newDealsCount, 'new exploration deals to deals.jsonl');
  console.log(`📊 Total deals now: ${allDeals.length}`);
  
  // Create a summary of added deals
  const addedDeals = explorationDeals.filter(d => !existingIds.has(d.id));
  console.log('\n🎉 Added deals:');
  addedDeals.forEach(deal => {
    console.log(`  • ${deal.name}: ${deal.deal}`);
  });
  
  // Check category compliance
  const validCategories = [
    'Hosting & Cloud', 'Database', 'APIs & Email', 'APIs & Payments',
    'APIs & Search', 'AI & LLM', 'Auth', 'Developer Tools',
    'Monitoring', 'Domains & Hosting', 'Storage & Cloud', 'Security',
    'Productivity', 'SEO', 'AI', 'Social Media', 'Customer Support',
    'Sales & Marketing', 'Services', 'Design & Collaboration',
    'Web Analytics', 'Media & Images', 'CI/CD', 'Testing & QA'
  ];
  
  const invalidCategories = addedDeals.filter(d => !validCategories.includes(d.category));
  if (invalidCategories.length > 0) {
    console.log('\n⚠️  Warning: Found deals with invalid categories:');
    invalidCategories.forEach(deal => {
      console.log(`  • ${deal.name}: ${deal.category} (valid categories: ${validCategories.join(', ')})`);
    });
  }
}

aggregateDeals().catch(console.error);